# Generated by Django 5.1.7 on 2025-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemonstracaoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('registro_ans', models.BigIntegerField(db_index=True)),
                ('cd_conta_contabil', models.BigIntegerField()),
                ('descricao', models.CharField(db_index=True, max_length=150)),
                ('vl_saldo_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vl_saldo_final', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('registro_ans', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=18)),
                ('razao_social', models.TextField()),
                ('nome_fantasia', models.TextField(blank=True, null=True)),
                ('modalidade', models.TextField()),
                ('logradouro', models.TextField()),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('ddd', models.CharField(max_length=3)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_eletronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('representante', models.TextField()),
                ('cargo_representante', models.TextField()),
                ('regiao_de_comercializacao', models.IntegerField(blank=True, null=True)),
                ('data_registro_ans', models.DateField()),
            ],
        ),
    ]
